### ISSUE TITLE
Jelly Force Closes

### ISSUE THREAD

**Issue by wasimafser** [DotOS/android_packages_apps_Jelly#3]
The jelly Browser Force closes.

Logs provide the following details : 

> W/lineageos.jell( 4370): Accessing hidden method Landroid/security/NetworkSecurityPolicy;->setCleartextTrafficPermitted(Z)V (dark greylist, linking)
W/lineageos.jell( 4370): Accessing hidden method Landroid/security/NetworkSecurityPolicy;->setCleartextTrafficPermitted(Z)V (dark greylist, linking)
D/AndroidRuntime( 4370): Shutting down VM
--------- beginning of crash
E/AndroidRuntime( 4370): FATAL EXCEPTION: main
E/AndroidRuntime( 4370): Process: org.lineageos.jelly, PID: 4370
E/AndroidRuntime( 4370): java.lang.NoSuchMethodError: No virtual method setCleartextTrafficPermitted(Z)V in class Landroid/security/NetworkSecurityPolicy; or its super classes (declaration of 'android.security.NetworkSecurityPolicy' appears in /system/framework/framework.jar!classes2.dex)
E/AndroidRuntime( 4370): 	at org.lineageos.jelly.utils.NetworkSecurityPolicyUtils.setCleartextTrafficPermitted(NetworkSecurityPolicyUtils.java:31)
E/AndroidRuntime( 4370): 	at org.lineageos.jelly.JellyApp.setClearTextTrafficConfig(JellyApp.java:40)
E/AndroidRuntime( 4370): 	at org.lineageos.jelly.JellyApp.onCreate(JellyApp.java:30)
E/AndroidRuntime( 4370): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
E/AndroidRuntime( 4370): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5926)
E/AndroidRuntime( 4370): 	at android.app.ActivityThread.access$1100(ActivityThread.java:201)
E/AndroidRuntime( 4370): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1657)
E/AndroidRuntime( 4370): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 4370): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 4370): 	at android.app.ActivityThread.main(ActivityThread.java:6724)
E/AndroidRuntime( 4370): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4370): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
E/AndroidRuntime( 4370): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W/ActivityManager( 1166):   Force finishing activity org.lineageos.jelly/.MainActivity
I/ActivityManager( 1166): Showing crash dialog for package org.lineageos.jelly u0

Checked for the class and the class exists in the desired location ( in the source ).
Maybe it didn't compile to the `frameworks.jar->classes2.dex` ?

Any Solution for this ?
[alogcat.2019-06-25-16-26-04-0600.txt](https://github.com/DotOS/android_packages_apps_Jelly/files/3328278/alogcat.2019-06-25-16-26-04-0600.txt)

**Comment by mohancm** [comment]
still investigating
